import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const GA_ID = process.env.GA_ID

  return (
    <html lang="en">
      <head>
        {/* <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
        window.dataLayer = window.dataLayer || [];
        unction gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '${GA_ID}');`}
        </Script> */}
      </head>
      <body className="page">
        <Sidebar />
        <div className="main">
          {children}
        </div>
      </body>


    </html>
  );
}
